### ISSUE TITLE
Sample config file with user and others

### ISSUE THREAD

**Issue by bikerboymohit** [paviro/MMM-Facial-Recognition#11]
Can the successful implementers please post their config.js file (You can just post this module part) with user class and a class defined for others so I know how I can configure mine.
Appreciate your help!

**Comment by paviro** [comment]
Please check out http://forum.magicmirror.builders for non issue related help.

**Comment by bikerboymohit** [comment]
Thank you. I wasn't sure where to post this hence posted it here.
#postclosed.
