### ISSUE TITLE
Facetrainer is not working with glasses

### ISSUE THREAD

**Issue by atilie** [paviro/MMM-Facial-Recognition#21]
Hi Paviro,

thanks for this awesome module. I got everything working so far.

Unfortunately I am wearing (massive) glasses. :) When I try to use the facetrainer (capture.py) it does not detect a single face. As soon as i take off the glasses everything works as expected. Is there any way to get the trainer working with glasses?

**Comment by paviro** [comment]
Hi there,
This module uses opencv for the recognition stuff. You can try to find out if there is a chance to get opencv working with glasses but I sadly highly doubt it :/
