### ISSUE TITLE
Capture.py option [2] give no reaction 

### ISSUE THREAD

**Issue by MrPineMan** [paviro/MMM-Facial-Recognition#25]
Hi Paviro, 

I'm started clean again to remove al the useless moves i made while testing. 
But when i doing exacly the same as before, running `capture.py`, and select option [2] to convert images. 
He don't do anything, the annyoing part is that he doens't give an error :| 
check out the screenshot. 

Do you have experience with the issue ? and is there any log folder? where i can trackback errors to search specific?

Any suggestion's are usefull! 
Thanks :)

![capture](https://cloud.githubusercontent.com/assets/17926205/20679244/5de18ddc-b59a-11e6-905d-d8fa71aa739e.PNG)

**Comment by paviro** [comment]
What format do the images have?

**Comment by MrPineMan** [comment]
Check the attachment I added. But it is, jpg.

**Comment by vanimesh76** [comment]
The training and recognition algorithm works best if they are done using the same camera, preferably pi-Camera.

**Comment by paviro** [comment]
@Labzz could you send me the pics so I can do some tests?
@vanimesh76 correct :)

**Comment by MrPineMan** [comment]
Ill send you my selfie Collection later Today, what is your email adress?

**Comment by paviro** [comment]
https://paulvincentroll.com/impressum.html

**Comment by MrPineMan** [comment]
@paviro I've found a funny but interesting thing ^_^ and it fixed my issue lol! 

PROTIP
-----------------------------------------

If you're running option [2] from the `capture.py` in the training module. 

Don't use folder path like this --> ~/your_path/
But simple use this --> /home/pi/your_path/

I think the ~ symbol ruined the script. LMAO 

Anyways thanks for you're help pivaro

**Comment by paviro** [comment]
That's interesting haven't thought about that! Could you add a warning to the Readme?
