### ISSUE TITLE
Deciding whether to use offline or online face recognition solutions

### ISSUE THREAD

**Issue by ghost** [paviro/MMM-Facial-Recognition#30]
Hi,
I have just decided to go from Magic Mirror 1 to 2 and I'm wondering.

1. What pros and cons between this solution and [Microsoft Cognitive service](https://www.google.com.au/webhp?sourceid=chrome-instant&rlz=1C1CHBF_en-GBAU716AU716&ion=1&espv=2&ie=UTF-8#q=microsoft+cognitive+services) other than the obvious online vs offline?
2. We might need to have a similar setup in several rooms. Can this solution support shared face storage?

Magic Mirror 1 implementation: https://github.com/MicrosoftEdge/magic-mirror-demo/blob/master/public/js/authenticate.js 

PS: We don't have a beef machine to process data but we have no problem using W10 (IoT or not) for the Magic Mirror 1 solution.

JK

**Comment by paviro** [comment]
This is for issues only, please visit the forum for other questions.
However: 
1. Well it's offline and does not need to upload sensitiv image data to another server. Thats basically it :)
2. Sure just use the same training file :)
