### ISSUE TITLE
Facerecognition.py

### ISSUE THREAD

**Issue by vanimesh76** [paviro/MMM-Facial-Recognition#4]
on running Facerecognition.py individually

indexError: list index out of bounds
raceback (most recent call last):
  File "facerecognition.py", line 48, in <module>
    if json.loads(sys.argv[1])["RECOGNITION_ALGORITHM"] == 1:
IndexError: list index out of range

**Comment by paviro** [comment]
You can't run the version bundled with the module individually. It has to be started by the module! For testing use the one in the testing directory!
