### ISSUE TITLE
face recognition doesn't work

### ISSUE THREAD

**Issue by Leliekevertje** [paviro/MMM-Facial-Recognition#42]
Hi Paviro,

Thanks for the great feature, I really love it!

I've installed all the modules. Captured my face and the Facetrainer recognized my face. So far, so good. After that installed the MMM-Facial-Recognition module and put the training xml in this dir. I've seen it work for once. But unfortunately it doesn't work since than. Can you help me out?

I've put the code below in the config:

		{
			module: 'MMM-Facial-Recognition',
			config: {
		        	// 1=LBPH | 2=Fisher | 3=Eigen
			        recognitionAlgorithm: 1,
			        // Threshold for the confidence of a recognized face before it's considered a
			        // positive match.  Confidence values below this threshold will be considered
			        // a positive match because the lower the confidence value, or distance, the
			        // more confident the algorithm is that the face was correctly detected.
			        lbphThreshold: 50,
			        fisherThreshold: 250,
			        eigenThreshold: 3000,
			        // force the use of a usb webcam on raspberry pi (on other platforms this is always true automatically)
			        useUSBCam: false,
			        // Path to your training xml
			        trainingFile: 'modules/MMM-Facial-Recognition/training.xml',
			        // recognition intervall in seconds (smaller number = faster but CPU intens!)
			        interval: 2,
			        // Logout delay after last recognition so that a user does not get instantly logged out if he turns away from the mirror for a few seconds
			        logoutDelay: 15,
			        // Array with usernames (copy and paste from training script)
			        users: ['Manja', 'Rinus'],
			        //Module set used for strangers and if no user is detected
			        defaultClass: 'default',
			        //Set of modules which should be shown for every user
			        everyoneClass: 'everyone',
			        // Boolean to toggle welcomeMessage
			        welcomeMessage: true
 				}
		},

**Comment by paviro** [comment]
Play with the threshold and record better images. The threshold of the tester is much lower than on the mirror.
