### ISSUE TITLE
Recognizes faces but not name

### ISSUE THREAD

**Issue by ValentinDenis** [paviro/MMM-Facial-Recognition#51]
Hi,

We did everything according to the readme, we added two faces and obtained a Training.xml. But in the training.xml there is no reference to the names we entered. The recognition tool is working fine, it recognizes our faces with our name and a confidence, but once the training file is loaded with MMM-Facial-Recognition, it recognizes my face but not with my name ("Hello stranger" etc)

Did we forget a step or do anything wrong ?

Thanks !

Edit: on the logs we get a "User undefined with confidence null logged in"

**Comment by paviro** [comment]
Hi there,
Hello stranger means it did not recognize you. The module is a bit stricter as to when it accepts a face. Try playing with the threshold.

**Comment by ValentinDenis** [comment]
I just had a positive result with LBPH on a threshold of 70 (with 54 confidence). 
We'll keep trying with different algorithm and thresholds.
Could it be that I should train it with more pictures ? My friend and I both have glasses, maybe without them it could lead to better results ?

Thanks for the really quick answer anyway !

**Comment by paviro** [comment]
Glasses sadly don't work that well :/
