### ISSUE TITLE
questions about adding to the config.js

### ISSUE THREAD

**Issue by diverdennis** [paviro/MMM-Facial-Recognition#55]
Hello,

i added this to my config.js and it´s not working...MagicMirror start fails:

> 			
		{
			module: "MMM-Facial-Recognition",
			config: {
				// 1=LBPH | 2=Fisher | 3=Eigen
				recognitionAlgorithm: 1,
				// Threshold for the confidence of a recognized face before it's considered a
				// positive match.  Confidence values below this threshold will be considered
				// a positive match because the lower the confidence value, or distance, the
				// more confident the algorithm is that the face was correctly detected.
				lbphThreshold: 50,
				fisherThreshold: 250,
				eigenThreshold: 3000,
				// force the use of a usb webcam on raspberry pi (on other platforms this is always true automatically)
				useUSBCam: true,
				// Path to your training xml
				trainingFile: "/home/pi/MagicMirror/modules/MMM-Facial-Recognition/training.xml",
				// recognition intervall in seconds (smaller number = faster but CPU intens!)
				interval: 2,
				// Logout delay after last recognition so that a user does not get instantly logged out if he turns away from the mirror for a few seconds
				logoutDelay: 15,
				// Array with usernames (copy and paste from training script)
				users: [Dennis],
				//Module set used for strangers and if no user is detected
				defaultClass: "default",
				//Set of modules which should be shown for every user
				everyoneClass: "everyone",
				// Boolean to toggle welcomeMessage
				welcomeMessage: true
			}
		},

> 

Can´t find out whats wrong... Anyboy has an idea about this?

I would appreciate any help.

**Comment by paviro** [comment]
What exactly isn’t working? Can’t help you without details. Error log?

**Comment by diverdennis** [comment]
> pi@magicmirror:~/MagicMirror $ npm start

> magicmirror@2.3.1 start /home/pi/MagicMirror
> sh run-start.sh

>Starting MagicMirror: v2.3.1
Loading config ...
WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: helloworld.
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Sockets connected & modules started ...
Launching application.
Shutting down server...
Stopping module helper: updatenotification

<

if i remove the module from my config.js it runs...  it´s the config from the Module readme... but i can´t find syntax errors

**Comment by paviro** [comment]
I just copied it myself a few days ago and it worked. Please ask on the forum for syntax help. GitHub is only for bugs and feature requests in the code. 

But as a tip: Have you added a comma after the module before it?

**Comment by diverdennis** [comment]
thanks for the response.

yes i did add a comma and i can´t find errors with npm run config:check.

just don´t get it..
