### ISSUE TITLE
How to use the detected user name in compliments?

### ISSUE THREAD

**Issue by sata73** [paviro/MMM-Facial-Recognition#8]
Hi,
thank's for your great module!
I just wanted to ask, how I can use the detected user name in the compliments.
Do you have any idea?
Actually I thouhgt I use a custom notification, send the current user as payload (this.current_user) from MMM-Facial-Recognition.js socketNotificationReceived and receive it in compliments.js with notificationReceived and start this.getDom(payload) - but it doesn't work.
Any help would be appreciated since I'm totally new to js.

**Comment by paviro** [comment]
The current user is already send as a notification I think (not sure quite a while since I last worked on it). If you need help check out the development section of http://forum.magicmirror.builders!
